name: lando-pantheon-plugin
services:
  cli:
    api: 3
    type: lando
    services:
      image: node:18
      command: sleep infinity
      working_dir: /app
      ports:
        - 8080:8080
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
tooling:
  node:
    service: cli
  vuepress:
    service: cli
  yarn:
    service: cli
