name: docs.pantheon
proxy:
  cli:
    - docs.pantheon.lndo.site:5173
services:
  cli:
    api: 4
    image: node:20
    command: sleep infinity
    ports:
      - 5173:5173/http
    scanner: false
    user: node
    build:
      app: |
        npm install
tooling:
  node:
    service: cli
  npm:
    service: cli
  vitepress:
    service: cli
    cmd: npx vitepress
