name: pantheon-downstreamer-2
recipe: pantheon

services:
  database:
    type: pantheon-mysql:8.0

# do not remove this
plugins:
  "@lando/pantheon": ../..
  "@lando/mysql": ../../node_modules/@lando/mysql
