name: Build Pantheon Images

on:
  # Uncomment below for testing purposes
  pull_request:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-22.04
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: pantheon-index
            tag: 3.6-3
            context: recipes/pantheon/3.6-solr
          - image: pantheon-index
            tag: 8.8-4
            context: recipes/pantheon/8.8-solr
          - image: pantheon-appserver
            tag: 8.2-4
            context: recipes/pantheon/8.2-fpm
          - image: pantheon-appserver
            tag: 8.1-4
            context: recipes/pantheon/8.1-fpm
          - image: pantheon-appserver
            tag: 8.0-4
            context: recipes/pantheon/8.0-fpm
          - image: pantheon-appserver
            tag: 7.4-4
            context: recipes/pantheon/7.4-fpm
          - image: pantheon-appserver
            tag: 7.3-4
            context: recipes/pantheon/7.3-fpm
          - image: pantheon-appserver
            tag: 7.2-3
            context: recipes/pantheon/7.2-fpm
          - image: pantheon-appserver
            tag: 7.1-3
            context: recipes/pantheon/7.1-fpm
          - image: pantheon-appserver
            tag: 7.0-3
            context: recipes/pantheon/7.0-fpm
          - image: pantheon-appserver
            tag: 5.6-3
            context: recipes/pantheon/5.6-fpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set tag suffix
        id: pr
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "tag-suffix=-edge" >> $GITHUB_OUTPUT
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devwithlando/${{ matrix.image }}:${{ matrix.tag }}${{ steps.pr.outputs.TAG_SUFFIX }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
